import random

print("To choose the story to play the game please type 1-3 or type 4 for a random story")
a = int(input("Type a number 1-4: "))
if a == 4:
    a = random.randint(1, 3)

if a == 1:
    print("Input a number:")
    number = input()
    print("Input a measure of time:")
    time_measure = input()
    print("Input a mode of transportation:")
    transportation_mode = input()
    print("Input an adjective:")
    adjective1 = input()
    print("Input another adjective:")
    adjective2 = input()
    print("Input a noun:")
    noun1 = input()
    print("Input a color:")
    color = input()
    print("Input a part of the body:")
    body_part = input()
    print("Input a verb:")
    verb = input()
    print("Input a number:")
    number2 = input()
    print("Input a noun:")
    noun2 = input()
    print("Input a noun:")
    noun3 = input()
    print("Input a part of the body:")
    body_part2 = input()
    print("Input a verb:")
    verb2 = input()
    print("Input a noun:")
    noun4 = input()
    print("Input an adjective:")
    adjective3 = input()
    print("Input a silly word:")
    silly_word = input()
    print("Input a noun:")
    noun5 = input()

    print(f"It was about {number} {time_measure} ago when I arrived at the hospital in a {transportation_mode}. The hospital is a/an {adjective1} place, there are a lot of {adjective2} {noun1} here. There are nurses here who have {color} {body_part}. If someone wants to come into my room I told them that they have to {verb} first. I’ve decorated my room with {number2} {noun2}. Today I talked to a doctor and they were wearing a {noun3} on their {body_part2}. I heard that all doctors {verb2} {noun4} every day for breakfast. The most {adjective3} thing about being in the hospital is the {silly_word} {noun5}!")
elif a == 2:
    print("Input a proper noun (person's name):")
    person_name = input()
    print("Input a noun:")
    noun = input()
    print("Input an adjective (feeling):")
    adjective_feeling = input()
    print("Input a verb:")
    verb = input()
    print("Input another adjective (feeling):")
    adjective_feeling2 = input()
    print("Input an animal:")
    animal = input()
    print("Input a verb:")
    verb2 = input()
    print("Input a color:")
    color = input()
    print("Input a verb (ending in ing):")
    verb_ing = input()
    print("Input an adverb (ending in ly):")
    adverb = input()
    print("Input a number:")
    number = input()
    print("Input a measure of time:")
    time_measure = input()
    print("Input a color:")
    color2 = input()
    print("Input an animal:")
    animal2 = input()
    print("Input a number:")
    number2 = input()
    print("Input a silly word:")
    silly_word = input()
    print("Input a noun:")
    noun2 = input()

    print(f"This weekend I am going camping with {person_name}. I packed my lantern, sleeping bag, and {noun}. I am so {adjective_feeling} to {verb} in a tent. I am {adjective_feeling2} we might see a(n) {animal}, I hear they’re kind of dangerous. While we’re camping, we are going to hike, fish, and {verb2}. I have heard that the {color} lake is great for {verb_ing}. Then we will {adverb} hike through the forest for {number} {time_measure}. If I see a {color2} {animal2} while hiking, I am going to bring it home as a pet! At night we will tell {number2} {silly_word} stories and roast {noun2} around the campfire!")
elif a == 3:
    print("Input a proper noun (person's name):")
    person_name = input()
    print("Input an adjective:")
    adjective = input()
    print("Input a color:")
    color = input()
    print("Input an animal:")
    animal = input()
    print("Input a place:")
    place = input()
    print("Input another adjective:")
    adjective2 = input()
    print("Input a magical creature (plural):")
    magical_creature_plural = input()
    print("Input another adjective:")
    adjective3 = input()
    print("Input another magical creature (plural):")
    magical_creature_plural2 = input()
    print("Input a room in a house:")
    room_in_a_house = input()
    print("Input a noun:")
    noun = input()
    print("Input a noun:")
    noun2 = input()
    print("Input a plural noun:")
    plural_noun3 = input()
    print("Input an adjective:")
    adjective4 = input()
    print("Input a plural noun:")
    plural_noun4 = input()
    print("Input a number:")
    number = input()
    print("Input a measure of time:")
    time_measure = input()
    print("Input a verb ending in ing:")
    verb_ing = input()
    print("Input an adjective:")
    adjective5 = input()
    print("Input a noun:")
    noun5 = input()

    print(f"Dear {person_name}, I am writing to you from a {adjective} castle in an enchanted forest. I found myself here one day after going for a ride on a {color} {animal} in {place}. There are {adjective2} {magical_creature_plural} and {adjective3} {magical_creature_plural2} here! In the {room_in_a_house} there is a pool full of {noun}. I fall asleep each night on a {noun2} of {plural_noun3} and dream of {adjective4} {plural_noun4}. It feels as though I have lived here for {number} {time_measure}. I hope one day you can visit, although the only way to get here now is {verb_ing} on a {adjective5} {noun5}!!")
